USE OperationsManager
GO
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.AlertsQueueHistory
	(
	QID uniqueidentifier DEFAULT NEWID() NOT NULL,
	AlertID uniqueidentifier NOT NULL,
	SubscriptionID uniqueidentifier NOT NULL,
	Source nvarchar(255) NULL,
	isChangeState tinyint NULL,
	Description nvarchar(255) NULL,
    TimeStmp DateTime NOT NULL    
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.AlertsQueueHistory ADD CONSTRAINT
	PK_AlertsQueueHistory PRIMARY KEY CLUSTERED 
	(
	QID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.AlertsQueueHistory SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

